name: Deploy Azure Container App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} ./src
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}

      - name: Replace image tag in containerapp.yaml
        run: |
          sed -i "s|<ACR_LOGIN_SERVER>/<IMAGE_NAME>:<TAG>|${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}|g" ${{ github.workspace }}/containerapp.yaml

      - name: Deploy Container App using YAML
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: my-container-app-rg
          yamlConfigPath: ${{ github.workspace }}/containerapp.yaml